<?php

namespace AppBundle\Repository;

/**
 * genusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;


class genusRepository extends \Doctrine\ORM\EntityRepository
{
 
    /**
     * 
     * @return Genus[]
     */
    
    public function findAllpublishedOrderedBySize()
    {
       
                  return $this->createQueryBuilder('genus')
            ->andWhere('genus.isPublished = :isPublished')
            ->setParameter('isPublished', true)
            ->orderBy('genus.speciesCount', 'DESC')
            ->getQuery()
            ->execute();
                
    }
    
    
}
